### ISSUE TITLE
Dockerfile cleanups do not minimize image size

### ISSUE THREAD

**Issue by radmen** [Zenika/alpine-chrome#1]
Hey,

first of all - thank you for this repo. You helped me in solving quite an annoying issue.
Thank you!

Secondly, I've found in Dockerfile quite intriguing lines:
https://github.com/Zenika/alpine-chrome/blob/2d0b861ca4a2a3c964d4db83e77d27d7e947ba41/Dockerfile#L22-L31

Just wanted to mention that this will not minimize image size.

Each command creates a layer. Each layer adds a size of **appended** changes. Running cleanup commands in a separate layer will append 0-byte changes. It won't affect overall image size

There're few ways to fix this:
* build image with `--squash` option
* append cleanup tasks to previous `RUN`
* create a separate installation script, copy it to image and run. This will create only two layers of changes (`COPY` of script and `RUN` which will install&cleanup)

Cheers! :)

**Comment by jlandure** [comment]
Hi @radmen 
👋 Thanks for your reply! 
👉 You're totally right! I will change that.
