### ISSUE TITLE
Unable to run it in Jenkins

### ISSUE THREAD

**Issue by HackPoint** [Zenika/alpine-chrome#11]
Error response from daemon: Container is not running

**Comment by jlandure** [comment]
Hi @HackPoint 
Thanks for your feedback. 👌 
Can you describe the `docker command` you're launching?
There is 3 ways to use Chrome Headless with this image
- Not secured
- With SYS_ADMIN capability
- The best: With seccomp

**Comment by jlandure** [comment]
Hi @HackPoint 
Any news to improve this image and help you with your jenkins problem?

**Comment by jlandure** [comment]
Hi @HackPoint 
Last call, I will close the issue in 3 days if you do not give any news...
