### ISSUE TITLE
npm not found

### ISSUE THREAD

**Issue by labs-scnm** [Zenika/alpine-chrome#14]
Hi,

`npm` has not been found since the last update.

BR
Sebastian

**Comment by labs-scnm** [comment]
Sorry, my mistake. You separate the images and moved it to the tag `with-node`.

**Comment by labs-scnm** [comment]
BTW: Thanks a lot for your great work! 🤗

**Comment by jlandure** [comment]
You're welcome @labs-scnm ! 👌

I've moved `node` (and `npm` `yarn`) in the ":with-node" version to reduce the size of the standard `alpine-chrome`
_We moved from ~200Mb to ~100Mb for the "standard" image._
_The one with `node` stay around ~185Mb._
_Details [here](https://hub.docker.com/r/zenika/alpine-chrome/tags/)_

Feel free to report desired enhancement or any issue using this image.
