### ISSUE TITLE
ERROR: unable to select packages:   so:libdav1d.so.4 (no such package):

### ISSUE THREAD

**Issue by johnykov** [Zenika/alpine-chrome#146]
**Describe the bug**
when I try to build latest Docker file I get this error
Executing busybox-1.32.0-r7.trigger
OK: 6 MiB in 14 packages
ERROR: unable to select packages:
  so:libdav1d.so.4 (no such package):
    required by: ffmpeg-libs-4.3.1-r2[so:libdav1d.so.4]

**To Reproduce**

1. try to build main Dockerfile
2. See error
OK: 6 MiB in 14 packages
ERROR: unable to select packages:
  so:libdav1d.so.4 (no such package):
    required by: ffmpeg-libs-4.3.1-r2[so:libdav1d.so.4]
3. and build stops

**Comment by jlandure** [comment]
Hi @johnykov 👋 

Thanks for submitting your issue. 👍 
I don't have any problems with the autobuild on DockerHub and I didn't get any errors on my laptop.

Could you give more information or retest the build? 😊 
Thanks!

**Comment by jlandure** [comment]
Hi @johnykov 👋 

Any updates? 👍 

Without news, I will close the issue in a few days. 😊

**Comment by jlandure** [comment]
Hi @johnykov 👋 

No news since one month so I close this issue. 
Feel free to add more details if you still encounter the problem. 👍
