### ISSUE TITLE
chromium-browser segfaults :(

### ISSUE THREAD

**Issue by c24w** [Zenika/alpine-chrome#15]
I can't get either of the latest `zenika/alpine-chrome` or `zenika/alpine-chrome:with-node` images to successfully launch a browser.  If I expand one of the readme examples, this is what happens:

```shell
> docker run -it --rm --entrypoint sh zenika/alpine-chrome
> /usr/src/app $ chromium-browser --headless --disable-gpu --disable-software-rasterizer --disable-dev-shm-usage --no-sandbox --dump-dom https://www.chromestatus.com/
Segmentation fault
```

The only way I've got that example to work is by using the image tagged `zenika/alpine-chrome:13`.

Do you know what's going on?

**Comment by jlandure** [comment]
Hi @c24w 👋 
First, thanks for your report.

I tried your command and I do not get `Segmentation fault` using the latest `zenika/alpine-chrome`...
Can you add more information using `--log-level=0` like in this command:
```
chromium-browser --log-level=0 --headless --disable-gpu --disable
-software-rasterizer --disable-dev-shm-usage --no-sandbox --dump-dom https://git
hub.com/Zenika/alpine-chrome/issues/15
```
I got these logs before the dom:
```
/usr/src/app $ chromium-browser --log-level=0 --headless --disable-gpu --disable
-software-rasterizer --disable-dev-shm-usage --no-sandbox --dump-dom https://git
hub.com/Zenika/alpine-chrome/issues/15
[0923/123843.959372:WARNING:dns_config_service_posix.cc(333)] Failed to read DnsConfig.
[0923/123843.964534:ERROR:gpu_process_transport_factory.cc(1016)] Lost UI shared context.
[0923/123844.251486:ERROR:nss_ocsp.cc(601)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[0923/123844.251539:ERROR:nss_ocsp.cc(601)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[0923/123844.251568:ERROR:nss_ocsp.cc(601)] No URLRequestContext for NSS HTTP handler. host: crl4.digicert.com
[0923/123844.253192:ERROR:nss_ocsp.cc(601)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[0923/123844.253252:ERROR:nss_ocsp.cc(601)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[0923/123844.253289:ERROR:nss_ocsp.cc(601)] No URLRequestContext for NSS HTTP handler. host: crl4.digicert.com
<!DOCTYPE html>
... 
```

**Comment by c24w** [comment]
Hi @jlandure!  Thanks for your reply.

I haven't got to the bottom of this yet, but just to update:

 - I'm running Arch Linux and it works when I do the same commands on Ubuntu (using the same version of Docker).
 - `--log-level=0` doesn't yield any extra information. :disappointed:
 - I get the same segfault if I build the [`Dockerfile`](https://github.com/Zenika/alpine-chrome/blob/94cee53b5e66cf8919c143a0540c0efe44b89a14/Dockerfile) on Arch (unsurprisingly).

**Comment by jlandure** [comment]
Hi @c24w 
Sorry, I've to admit: I didn't test this image on Arch 😅

Do you get "chromium" working on your Arch installation? Is it a `x86-64 Linux` or a `ARM` architecture?
Do you think it's related to this Arch [bug](https://bugs.archlinux.org/task/58269)?

**Comment by c24w** [comment]
I can't blame you :grin:

I've just installed a fresh version of Chromium 69.0.3497.100 Arch Linux, from the official repositories, and it works fine.  I'll not sure what version is installed in the `latest` of your images, so I'll check that next.

It's using `x86_64 GNU/Linux`.

That bug seems to relate to a `~/.config/chromium-flags.conf` file, which isn't present in your images :thinking:.

I'll keep digging...

**Comment by jlandure** [comment]
Using `apk` I can only get the version described [here](https://git.alpinelinux.org/cgit/aports/log/community/chromium)
The latest chromium available for the `alpine` distribution is `68.0.3440.106`

**Comment by jlandure** [comment]
Hi @c24w 👋 
Do you still have `Segmentation fault` issue with or can I close this issue? 👍 
Thanks for your reply!

**Comment by c24w** [comment]
Just tried again against latest and it seems to work fine, so issue resolved from my perspective :)

**Comment by jlandure** [comment]
Thanks @c24w ! 🎉

**Comment by jlandure** [comment]
@all-contributors please add @c24w for bug
