### ISSUE TITLE
alpine-chrome:68 no longer working

### ISSUE THREAD

**Issue by donofriov** [Zenika/alpine-chrome#154]
We have been using alpine-chrome:68 and as of 3 days ago our production application started failing because alpine-chrome:68 can no longer be started.

I see that 68 has been removed from the GitHub [releases](https://github.com/Zenika/alpine-chrome/releases) and [tags](https://github.com/Zenika/alpine-chrome/tags), would that have any affect on the docker hub image? https://hub.docker.com/layers/zenika/alpine-chrome/68/images/sha256-07455c3ea22355829bc16cc013e20a8aeaea606d13c915073ee9a17627195ec4?context=explore

**Comment by jlandure** [comment]
Hello @donofriov 👋 

Thanks for submitting your issue! 👍 
FYI, the GitHub releases don't reflect the Docker [tags available in the Docker Hub](https://hub.docker.com/r/zenika/alpine-chrome/tags).

The `68` version is still available here: https://hub.docker.com/layers/zenika/alpine-chrome/68/images/sha256-07455c3ea22355829bc16cc013e20a8aeaea606d13c915073ee9a17627195ec4?context=explore

Can you shared the detail of your problem? logs? command to launch the container?
Did you succeed with a more recent version of this `alpine-chrome`?

Thanks.

**Comment by jlandure** [comment]
Hi @donofriov 

Any updates?

**Comment by donofriov** [comment]
Hi @jlandure thanks so much for responding. We ended up upgrading to version `73` and the issue went away. 

For additional information, running

```
docker run --rm -it \
    --entrypoint="" \
    -p 3123:3123 \
    zenika/alpine-chrome:68 \
        chromium-browser \
        --no-sandbox \
        --remote-debugging-address=0.0.0.0 \
        --remote-debugging-port=3123 \
        --headless \
        --disable-gpu \
        --disable-software-rasterizer
```

Resulted in a seg fault

```
fails 139 exit code (seg fault), no output
```

I don't have the exact output from 73 where we ended up but we were also to get it working with 71 and 86

```
docker run --rm -it \
    --entrypoint="" \
    -p 3123:3123 \
    zenika/alpine-chrome:71 \
        chromium-browser \
        --no-sandbox \
        --remote-debugging-address=0.0.0.0 \
        --remote-debugging-port=3123 \
        --headless \
        --disable-gpu \
        --disable-software-rasterizer
[0122/163622.897440:WARNING:dns_config_service_posix.cc(334)] Failed to read DnsConfig.
[0122/163622.915835:ERROR:gpu_process_transport_factory.cc(967)] Lost UI shared context.
DevTools listening on ws://0.0.0.0:3123/devtools/browser/1a08bc12-28e4-4feb-adc5-645f72c6e671
```

```
docker run --rm -it \
    --entrypoint="" \
    -p 3123:3123 \
    zenika/alpine-chrome:86 \
        chromium-browser \
        --no-sandbox \
        --remote-debugging-address=0.0.0.0 \
        --remote-debugging-port=3123 \
        --headless \
        --disable-gpu \
        --disable-software-rasterizer
[0122/163825.509806:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0122/163825.510911:WARNING:dns_config_service_posix.cc(342)] Failed to read DnsConfig.
DevTools listening on ws://0.0.0.0:3123/devtools/browser/6e0a905a-75cf-4487-90bb-9ce98104778e
[0122/163825.579076:WARNING:dns_config_service_posix.cc(342)] Failed to read DnsConfig.
```

There are errors on the new versions but they aren't affecting out functionality at all so we were able to restore our production services.

I'm going to close this. Thanks again!

**Comment by jlandure** [comment]
Hey @donofriov 👋 

If you don't mind, could you create a issue of this kind: https://github.com/Zenika/alpine-chrome/issues/new?assignees=&labels=&template=03_thanks.md to explain your usecase and how this image helps you? Perhaps with the logo of your company to create a "Used by" section in the README. 👍 

What do you think? 🤔
