### ISSUE TITLE
Publish image for arm

### ISSUE THREAD

**Issue by dzek69** [Zenika/alpine-chrome#16]
Hi, it would be awesome if you could publish images for ARM for running on Raspberry devices.

**Comment by jlandure** [comment]
Hi @dzek69 👋 
I'm happy to help. 

Could you give more details about your request?

According to the [official docs on Docker](https://github.com/docker-library/official-images#architectures-other-than-amd64), there is an dedicated subgroup on DockerHub for `arm32v7` here: https://hub.docker.com/u/arm32v7/
Just to be sure, do you want this kind of Docker image?

**Comment by dzek69** [comment]
Yeah.
You can make multiarch images (but I never did one), no need for special groups. I can for example run bare alpine just fine from the same source on standard PC and Raspberry.

What is probably a problem is that you will probably need an CPU on that architecture to create such image.

**Comment by jlandure** [comment]
Hi @dzek69 👋 
I will try to investigate using ARM CPU on AWS.
https://aws.amazon.com/fr/blogs/aws/new-ec2-instances-a1-powered-by-arm-based-aws-graviton-processors/

**Comment by dzek69** [comment]
Ok, thank you.

I'm waiting for the results then. Good luck 😄

**Comment by ck99** [comment]
Also interested in this.

I've had success building ARM images on x86 build machine using an approach like this:

https://matchboxdorry.gitbooks.io/matchboxblog/content/blogs/build_and_run_arm_images.html

**Comment by dgsb** [comment]
it's quite an old issue, but it's even more relevant with the new arm based apple laptop line.

**Comment by zigarn** [comment]
Solved by #201
