### ISSUE TITLE
Testing Chrome Extension with Puppeteer and Xvfb (Headful)

### ISSUE THREAD

**Issue by chriscamicas** [Zenika/alpine-chrome#167]
**Context**

Thank you for your work, this image was really helpful.
I want to test a chrome extension, but unfortunately it is not possible in headless mode [according to puppeteer official doc](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#working-with-chrome-extensions).
I can confirm, I tried ;-)

**Alternatives**

Currently, I can run the tests I need with a docker image I've built based on `zenika/alpine-chrome:with-puppeteer` where I add the installation of [Xvfb](https://en.wikipedia.org/wiki/Xvfb) and start it.

**Has the feature been requested before?**

No request found

**If the feature request is accepted, would you be willing to submit a PR?**

Yes, absolutely, I have the code available right away. I prefer to ask before submitting a PR since your repository objectives clearly mention the smallest headless image for e2e test ;)

**Comment by chriscamicas** [comment]
you can have a look right there: https://github.com/chriscamicas/alpine-chrome/tree/master/with-puppeteer-xvfb

**Comment by jlandure** [comment]
Hi @chriscamicas 👋 

Very interesting! 👍 
I suggest to create a PR if you have the time to do it! 💚 
You can submit an example here: https://github.com/Zenika/alpine-chrome/tree/master/examples/

WDYT?

Thanks!

**Comment by chriscamicas** [comment]
Thanks for your message, the PR is created : #174
