### ISSUE TITLE
propose: add tini to reape (possible) zombie process

### ISSUE THREAD

**Issue by jokester** [Zenika/alpine-chrome#17]
When building a [pptraas.com](https://github.com/GoogleChromeLabs/pptraas.com)-like service, I had to write this in Dockerfile (and they add to layers 😞):

```
USER root
RUN apk add tini
USER chrome
ENTRYPOINT ['tini', '--']
```

I am guessing the need to reape zombie process is common, can we add `tini` (or `dumb-init` or alike) to base image?

**Comment by jlandure** [comment]
Hi @jokester 👋 
I'm ok with your suggestion. I already create an issue for that #10  👌

**Comment by jlandure** [comment]
Hi @jokester 👋 
Just to be sure to reproduce the problem, can you explain the way you use this image?
Thansk! 👍

**Comment by jlandure** [comment]
@all-contributors please add @jokester for bug
