### ISSUE TITLE
Latest version is 89, Chrome is 94 – will there be an update?

### ISSUE THREAD

**Issue by alexbepple** [Zenika/alpine-chrome#184]
Hello, @jlandure. 

Let me use this opportunity to say a big thank you for zenika/alpine-chrome. Without it, my life would be a lot harder.

I am curious whether there are any updates on the books for alpine-chrome? I know that alpine-chrome has gone this long without new releases before. Just wondering …

Thank you!

**Comment by kalliub** [comment]
Good point! I'm waiting for the same update!
