### ISSUE TITLE
Getting symbol not found error

### ISSUE THREAD

**Issue by alexandru-calinoiu** [Zenika/alpine-chrome#19]
Building the image on archlinux and running 

```
chromium-browser --version
```

Will result in:

```
Error relocating /usr/lib/chromium/chrome: hb_font_funcs_set_glyph_h_advances_func: symbol not found
```

**Comment by jlandure** [comment]
Hi @alexandru-calinoiu Hi @utvk 👋 
I've added harfbuzz like suggested. Hope this helps!
Thanks by the way for you report! Have a nice DX with this docker image 👍

**Comment by jlandure** [comment]
@all-contributors please add @alexandru-calinoiu and @utvk for bug
