### ISSUE TITLE
Publish 100-with-chromedriver tag

### ISSUE THREAD

**Issue by jcestibariz** [Zenika/alpine-chrome#196]
Hi, I'm able to pull `zenika/alpine-chrome:with-chromedriver` but trying to pull `zenika/alpine-chrome:100-with-chromedriver` produces this error:

```sh
$ docker pull zenika/alpine-chrome:100-with-chromedriver
Error response from daemon: manifest for zenika/alpine-chrome:100-with-chromedriver not found: manifest unknown: manifest unknown
```

**Comment by zigarn** [comment]
Sadly, with the DockerHub autobuild all flavors were built at the same time and depending on `latest` parent image that was often not yet at latest version.
So there is no `100-with-chromedriver` and it's not possible to build it afterwards as this version of chromium is not available in alpine repo.
You can use `99-with-chromedriver` or `102-with-chromedriver`.

With new build with GitHub Actions, this should not happen anymore.

**Comment by jcestibariz** [comment]
I was able to pull `102-with-chromedriver` (which wasn't available when I filed this issue). Thank you.
