### ISSUE TITLE
100-with-puppetter works fine but with-puppetter fails

### ISSUE THREAD

**Issue by mjaggard** [Zenika/alpine-chrome#204]
**Describe the bug**
I get these errors when attempting to start Chrome

Error relocating /usr/lib/libre2.so.9: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEv: symbol not found
Error relocating /usr/lib/libre2.so.9: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /usr/lib/libsnappy.so.1: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /usr/lib/libsrt.so.1.4: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEv: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE7reserveEv: symbol not found

**To Reproduce**
`docker container run -it --rm --cap-add=SYS_ADMIN --entrypoint "" zenika/alpine-chrome:with-puppeteer chromium-browser --version`

**What is the expected behavior?**
The browse should run

**What is the actual behavior?**
The above error is printed and the browser fails to start

**Versions**
Client:
 Cloud integration: v1.0.22
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Built:             Thu Mar 10 14:08:44 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.6.1 (76265)
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Built:            Thu Mar 10 14:06:05 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.10
 runc:
  Version:          1.0.3
 docker-init:
  Version:          0.19.0

**Comment by zigarn** [comment]
Fixed by c3f32c2b102c1ee2efd46fa4833491d7e956afaa
