### ISSUE TITLE
alpine-chrome:with-node has non-working chrome

### ISSUE THREAD

**Issue by eni23** [Zenika/alpine-chrome#205]
**Describe the bug**

The latest version of `zenika/alpine-chrome:with-node` (Digest: `sha256:33b4072d8e7e5c95fc48d0a3d66cd3bbf965e5e98ab0d89dc981894d39ba80c8`) ships a broken chrome version

**To Reproduce**

```
docker run -it --rm zenika/alpine-chrome@sha256:33b4072d8e7e5c95fc48d0a3d66cd3bbf965e5e98ab0d89dc981894d39ba80c8 sh
chromium-browser --version
```
returns:
```
Error relocating /usr/lib/libre2.so.9: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEv: symbol not found
Error relocating /usr/lib/libre2.so.9: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /usr/lib/libsnappy.so.1: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /usr/lib/libsrt.so.1.4: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZSt28__throw_bad_array_new_lengthv: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEv: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE7reserveEv: symbol not found
```

**What is the expected behavior?**
As with the previous version:
```
docker run -it --rm zenika/alpine-chrome@sha256:716314b5a114c912d3ea408d12872f0253d6cc9f02807b1f44e5cedf0abadf5e sh
chromium-browser --version
```
it should return something like this:
```
Chromium 102.0.5005.61
```

**Possible solution**

This Symbols should be included in `libstdc++` so this package needs to be installed.

**Versions**

| Software      | Version(s)   | How-to                                                                                          |
| ------------- | ------------ | ----------------------------------------------------------------------------------------------- |
| Chromium      | ? | `docker container run -it --rm --entrypoint "" zenika/alpine-chrome chromium-browser --version` |
| Image         | zenika/alpine-chrome@sha256:33b4072d8e7e5c95fc48d0a3d66cd3bbf965e5e98ab0d89dc981894d39ba80c8ad3dc8       | `docker image inspect --format='{{index .RepoDigests 0}}' zenika/alpine-chrome`                 |
| Docker Engine | 20.10.16|        `docker version`                                                                                |

**Additional context**

**Comment by zigarn** [comment]
Fixed by c3f32c2b102c1ee2efd46fa4833491d7e956afaa
