### ISSUE TITLE
Existing docker images based on alpine-chrome:with-puppeteer are now broken

### ISSUE THREAD

**Issue by DJFliX** [Zenika/alpine-chrome#21]
Since this [commit](https://github.com/Zenika/alpine-chrome/commit/05af669e674498ffc48f9223b8c286a6db74ed7e) my build pipeline is broken. 

My docker image did this in the final step:
`CMD ["node", "run"]`

And it seems that having `tini` set as the entrypoint breaks this behaviour. 

Of course I can fix this in my `Dockerfile` but this won't fix old revisions of images that are based off of `alpine-chrome:with-puppeteer`. Was it a conscious decision to break existing behaviour?

**Comment by jlandure** [comment]
Hi @DJFliX 👋 
Thanks for your feedback. 👍 
Honestly, I didn't know that adding `tini` in the entrypoint could affect another `CMD`. 😓 

Can you try launching your Docker image running `docker container run -it [your params] --entrypoint "" zenika/alpine-chrome:with-puppeteer` to check it's always working? 👌 

And I'm curious. What does the `CMD ["node", "run"]`? 🤔

**Comment by jlandure** [comment]
Hey @DJFliX 

I was reading your comment: you didn't need to fix older versions of your images. You're safe if they are already built. I know the current `tini` commit breaks existing behaviour but older ones are safe. Do you agree with that? 

Anyway, can we have a closer look to your problem? 😊

**Comment by DJFliX** [comment]
Hi @jlandure! Thanks for responding so quickly! So I was (ab)using your container because it contains all the dependencies (including a version of puppeteer matching the version of chromium installed). But I had some quirks out of the box so I decided to add a CMD to my Dockerfile after adding my sources to fix the issue. 

So `CMD ["node", "run"]` runs my `run.js` with node. Because of the new ENTRYPOINT apparently it was trying to call tini instead of my app resulting in a process exit. 

I agree that older images won't have to be fixed, but re-running pipelines for older code revisions will now fail. I did work around the issue by overriding the ENTRYPOINT in our container runner (Amazon Elastic Container Service). It's possible that using `tini` instead of `CMD ["node", "run"]` might fix the quirks I experienced but right now I was just looking for an easy fix to repair my pipelines 😛 .

**Comment by jlandure** [comment]
Thanks for your reply @DJFliX 👍 
FYI, I've tried an equivalent of your `CMD` instruction and have no problem 🤔 
Example:
```
ls -R
Dockerfile src

./src:
pdf.js
```
Dockerfile:
```
FROM zenika/alpine-chrome:with-puppeteer
CMD ["node", "src/pdf"]
```
Build command: `docker build -t zenika/example .`
Launch command: `docker container run -it --rm -v $(pwd)/src:/usr/src/app/src --cap-add=SYS_ADMIN zenika/example`

Can you help me describing your error? logs perhaps? 👌

**Comment by jlandure** [comment]
Hi @DJFliX 
Do you any updates to share? 
Thanks! 👍

**Comment by jlandure** [comment]
Hi @DJFliX 👋 
Last call for any updates to share? Thanks!

**Comment by DJFliX** [comment]
Hi Julien,

I’m very sorry but I haven’t had time to look into it further. For me the workaround seems to be working okay so imo we can close the issue.

Kind regards,

Felix

**Comment by jlandure** [comment]
@all-contributors please add @DJFliX for bug
