### ISSUE TITLE
pulseaudio can't install in 102-with-puppeteer-xvfb

### ISSUE THREAD

**Issue by WisperDin** [Zenika/alpine-chrome#215]
**Describe the bug**
`FROM zenika/alpine-chrome:102-with-puppeteer-xvfb` 
I can't `apk add --no-cache pulseaudio` in this image

**To Reproduce**
Dockerfile:
```
FROM zenika/alpine-chrome:102-with-puppeteer-xvfb
USER 0

RUN apk update
RUN apk add --no-cache pulseaudio-alsa
RUN apk add --no-cache pulseaudio-utils
RUN apk add --no-cache pulseaudio

RUN pulseaudio --version
```

`docker build --no-cache  --progress=plain .`

Logs:
```
#8 [5/6] RUN apk add --no-cache pulseaudio
#8 sha256:8139863cf19317109532d4027e7fe2a126d0452e080a6ac164be76c740e17ae7
#8 6.484 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
#8 10.34 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
#8 14.51 ERROR: unable to select packages:
#8 14.61   mesa-21.3.8-r1:
#8 14.61     breaks: mesa-egl-21.3.8-r2[mesa=21.3.8-r2]
#8 14.61     satisfies: mesa-gl-21.3.8-r1[mesa=21.3.8-r1]
#8 14.61                mesa-gbm-21.3.8-r1[mesa=21.3.8-r1]
#8 ERROR: executor failed running [/bin/sh -c apk add --no-cache pulseaudio]: exit code: 3

```

**What is the expected behavior?**
install success and run `pulseaudio --version` return success

**Possible solution**
change the alpine version and install the pulseaudio

**Additional context**
I want to install pulseaudio , since I want to use ffmpeg to record video with sound in xvfb with chrome.

**Comment by zigarn** [comment]
Solved with latest `108-with-puppeteer-xvfb` based on Alpine 3.17.
