### ISSUE TITLE
unable to run with-puppeteer example

### ISSUE THREAD

**Issue by horacimacias** [Zenika/alpine-chrome#23]
thanks for the work; the image looks like exactly what I need.
However I'm having trouble executing the with-puppeteer example:

> docker run -it --rm -v $(pwd)/src:/usr/src/app/src --cap-add=SYS_ADMIN zenika/alpine-chrome:with-puppeteer node src/pdf.js
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"tini\": executable file not found in $PATH": unknown.
> 
I'm running in on docker for OSX, in case that matters.

I also tried building a modified image (basically commenting out the ENTRYPOINT with tini) and then I get this error instead:

> [0408/191634.027504:ERROR:headless_shell.cc(559)] Open multiple tabs is only supported when remote debugging is enabled.

Any clues on how can I troubleshoot or fix this?

**Comment by URSTYLE** [comment]
Define own entrypoint, e.g.:
```
chromium-browser --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 --hide-scrollbars --disable-dev-shm-usage
```

**Comment by jlandure** [comment]
Hi @horacimacias 👋 and thanks for the feedback
Hi @URSTYLE 👋 and thanks for the workaround. Is it working as expected @horacimacias ?

💭 Do you think it is interesting to add the flag `--remote-debugging-port=9222` by default in the javascript file `pdf.js`?  

**IMPORTANT**: As already described in the [README](https://github.com/Zenika/alpine-chrome#not-secured), be careful with the use of `--no-sandbox`.

**Comment by jlandure** [comment]
Hi @horacimacias and @URSTYLE  👋 
Any news on this issue?

**Comment by horacimacias** [comment]
sorry @jlandure; I was able to define my own entry point, and yes this works for me now. Thanks.

In my case I was trying to run the _How to use with Puppeteer_ example:

> docker run -it --rm -v $(pwd)/src:/usr/src/app/src --cap-add=SYS_ADMIN zenika/alpine-chrome:with-puppeteer node src/pdf.js

which still fails with the same _tini_ error. 
I'd suggest either the readme is updated or the image is updates so the samples provided on the readme work as they are described.

Regarding _remote-debugging-port_ yes I think is a good idea to add it by default. You can always use a different pdf.js or choose to export or not the port in docker.

**Comment by jlandure** [comment]
Hi @horacimacias 👋
Thanks again for your feedback and your time.

I've updated the example in the `with-puppeteer` folder. I don't have any errors.

Feel free to retry 👌 and if you still have an issue, please share the logs of the error. 👍

**Comment by horacimacias** [comment]
thanks @jlandure. It works for me now (if anybody else is having trouble make sure you _docker pull_ the image as in my case I was using an outdated)

Now the example as the README.md describes works fine for me.

**Comment by jlandure** [comment]
@all-contributors please add @horacimacias for bug
