### ISSUE TITLE
\"tini\": executable file not found in $PATH

### ISSUE THREAD

**Issue by emilkjer** [Zenika/alpine-chrome#24]
After adding `ENTRYPOINT ["tini", "--"]` it breaks the Puppeteer Docker image.

Reference commit:
https://github.com/Zenika/alpine-chrome/commit/7b4f2b3b527b3245a4a8ad893f0f4beb2bbf12b2#diff-c29f529b3e98482e07a5768ff85c139dR9

Reproduce by:
```
docker run -it --rm -v $(pwd)/src:/usr/src/app/src --cap-add=SYS_ADMIN zenika/alpine-chrome:with-puppeteer node src/pdf.js

docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"tini\": executable file not found in $PATH": unknown.
ERRO[0001] error waiting for container: context canceled
```

**Comment by jlandure** [comment]
Hi @emilkjer 👋 
Thanks for your feedback!
Can you check this issue #21 ? I have no problem using the command you gave:
```
docker run -it --rm -v $(pwd)/src:/usr/src/app/src --cap-add=SYS_ADMIN zenika/alpine-chrome:with-puppeteer node src/pdf.js
```

For your information, you can always override the `ENTRYPOINT` using `docker container run -it [your params] --entrypoint "" zenika/alpine-chrome ...`

**Comment by emilkjer** [comment]
Hi @jlandure 

Thanks for the quick response!

This is very odd, because when I build the image now everything goes fine. Could it be a faulty image on DockerHub that got fixed after you bumped the versions?

Your project is used with [React Snap](https://github.com/stereobooster/react-snap) and run by the Gitlab CI. It's the Gitlab runner which wasn't too happy about tini... I'm baffled, it works fine now both locally and run at Gitlab!?!?! 

Closing the issue!

Cheers
Emil

**Comment by jlandure** [comment]
Thanks @emilkjer for closing the issue. And sorry for this "weird" temporary problem.

And good to know you're using this image in [React Snap](https://github.com/stereobooster/react-snap). Perhaps I could add a "Used by" section in the README with some logos. What do you think?

**Comment by jlandure** [comment]
@all-contributors please add @emilkjer for bug
