### ISSUE TITLE
Permissions on mounted files

### ISSUE THREAD

**Issue by jlandure** [Zenika/alpine-chrome#3]
_From an email_

**How to read the image generated after the screenshot?**
The image is created into the mapped directory (to the volume) but the owner of the image is 1001 (root outside the container?):
`-rw------- 1 1001 1001 2454 mar  8 16:48 screenshot.png`

So I can't open the image until I've changed the permissions.

**Any idea how to solve it?**

**Comment by jllado** [comment]
Finally I've fixed it with the -u parameter:
docker container run -u `id -u $USER` --rm -v $(pwd):/usr/src/app zenika/alpine-chrome --no-sandbox --disable-gpu --screenshot --hide-scrollbars --window-size=386,250 http://www.google.co

**Comment by jlandure** [comment]
I let the issue opened to make a PR on the `README.md`

**Comment by jlandure** [comment]
Fixes by #4
