### ISSUE TITLE
Error on container launch: Failed to move to new namespace

### ISSUE THREAD

**Issue by SuddenGunter** [Zenika/alpine-chrome#30]
I've tried to use it in my docker image based on zenika/alpine-chrome.
see dockerfile here: https://github.com/SuddenGunter/pandaren/tree/master/cmd

It didn't work for me, so I just try tried to do docker run zenika/alpine-chrome - same error.

Error message (happens in both cases)

```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
[0625/214704.494573:FATAL:zygote_host_impl_linux.cc(187)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid).
Received signal 6
  r8: 00000000000000c1  r9: 00007fb2bce9314c r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffec57e1860 r13: 00000000000000a0 r14: 000055c1b5d4ba64 r15: 00007ffec57e1880
  di: 0000000000000002  si: 00007ffec57e1730  bp: 00007ffec57e1730  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fb2bce49fa0  sp: 00007ffec57e1718
  ip: 00007fb2bce49fa0 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

Environment:
macOS 10.14.5
docker v2.0.0.3 (31259), engine: 18.09.2

**Comment by SuddenGunter** [comment]
I've just ended up using bare alpine and installed chromium + dependencies + dumb init

**Comment by jlandure** [comment]
Hi @SuddenGunter 👋 

Sorry for the delay... And thanks for the report.

Your error is here because you cannot execute the `alpine-chrome` without security.
The different usecases are explained [here](https://github.com/Zenika/alpine-chrome#3-ways-to-use-chrome-headless-with-this-image).

You can test the image using the following command:

```
docker run zenika/alpine-chrome --no-sandbox
[0709/182256.661108:WARNING:dns_config_service_posix.cc(335)] Failed to read DnsConfig.
```

This command does nothing: only launch Chrome and quit the process.
I hope this helps. 

Does your new image fit your needs? Can I help you for something?

**Comment by aman4387** [comment]
after runnig image with --no-sandbox getting below error

ERROR:gpu_channel_manager.cc(398)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.

**Comment by jlandure** [comment]
Hi @aman4387 👋 

Can you please indicate me the version of the image `zenika/alpine-chrome` you are using? I have no such problem.

**Step 1**
Checkout latest version
```
docker image pull zenika/alpine-chrome
```

**Step 2**
Check version of the image
```
docker image inspect --format='{{index .RepoDigests 0}}' zenika/alpine-chrome
zenika/alpine-chrome@sha256:a768924d69a22bf014245e5f81a2f7cd04b656fa3a636df6e8d157aebcf4cc9a
```

**Step 3**
Launch with no version
```
docker container run zenika/alpine-chrome --no-sandbox           
[0813/144231.494902:WARNING:dns_config_service_posix.cc(335)] Failed to read DnsConfig.
```
