### ISSUE TITLE
Use image for PDF generation

### ISSUE THREAD

**Issue by wheestermans31** [Zenika/alpine-chrome#34]
**Context**

One of our projects has created some debian image with node+chrome installed to be able to create PDFs. 

But our standard for now of base images is alpine. Is you alpine-chrome image capable to do? I did a lot of reading about chrome and alpine, and came quickly to chromium installation. But the guy told me that chromium can't be used for the PDF generation, he needs the real chrome.

Regards
Walter

**Comment by jlandure** [comment]
Hi @wheestermans31 👋 
Thanks for your question 💭 

With this image, you can for the moment:
* Print a pdf directly from Chromium like explained [here](https://github.com/Zenika/alpine-chrome#print-a-pdf)
* Print a pdf using [Puppeteer](https://github.com/GoogleChrome/puppeteer) like explained [here](https://github.com/Zenika/alpine-chrome#how-to-use-with-puppeteer)

Have you tried one of these commands?

Regards,

**Comment by sibijohn72** [comment]
@wheestermans31 I am personally using chromium specifically for PDF conversion and it works. [Though not with this image at the moment but thats what i am trying to do now.] It doesnt matter whether you use chrome or chromium.

**Comment by walter-heestermans-toyota** [comment]
tested too and works

**Comment by jlandure** [comment]
Hi @sibijohn72 @walter-heestermans-toyota 👋 
Thanks for your comments! 👍 

Can you explain your main usage of this image?
Or at least the command you use to generate `pdf`? Is it with chromium command or with puppeteer? 🙌 

Have a great day.

**Comment by sibijohn72** [comment]
With puppeteer, more correctly with a library called puppeteersharp which is c# wrapper around puppeteer. What i plane to do with this image is set up a product like browserless.io

**Comment by jlandure** [comment]
Hey @wheestermans31 👋 
Are you still facing issues generating image with this image or can I close this issue?

**Comment by walter-heestermans-toyota** [comment]
You may close, team has tested and all fine now

walter

**Comment by jlandure** [comment]
@all-contributors please add @wheestermans31 for bug
