### ISSUE TITLE
chromium-browser not starting

### ISSUE THREAD

**Issue by ardeois** [Zenika/alpine-chrome#39]
**Describe the bug**
First I want to thank you for this image, which is really helpful for our build system.
However, since today it seems like chromium fails to start with, displaying the following error:
```
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```

It looks like this happens since the last image was pushed (5 hours ago)

**To Reproduce**

1. Execute `docker container run -it --rm --entrypoint "" zenika/alpine-chrome chromium-browser --version`
2. See error
```
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt19_Sp_make_shared_tag5_S_eqERKSt9type_info: symbol not found
```

I was able to reproduce the issue on multiple machines (mac and linux)

**What is the expected behavior?**
Chromium should be able to start and display its version

**What is the actual behavior?**
Chromium crashes

**Possible solutions**
I don't know yet but I'll try to dig in see if I find something.
If anybody knows how to fix it right away that would be greatly appreciated.

**Versions**

| Software      | Version(s)   | How-to                                                                                |
| ------------- | ------------ | ------------------------------------------------------------------------------------- |
| Chromium      | ? | `docker run -it --rm --entrypoint "" zenika/alpine-chrome chromium-browser --version` |
| Image         | zenika/alpine-chrome@sha256:794b317131be727d5b7489e42f28d62f400d1aa7ffade0948f0fd7942e9d27c9       | `docker image inspect --format='{{index .RepoDigests 0}}' zenika/alpine-chrome`       |
| Docker Engine | 19.03.2        | `docker version`                                                                      |

**Comment by teddy-error** [comment]
Cloning the Dockerfile and downgrading the Chromium version eliminated this error. Didn't test many due to crunch here but found no such issue with `chromium@edge=72.0.3626.121-r0`.

@ardeois The Chromium version you used (in the table ?) is `77.0.3865.75-r0`.

So, issue seems to be upstream

**Comment by robwilde** [comment]
@teddy-error could possibly share the line you changed in the docker file to adjust the version as I am not sure of the syntax.

Thanks

**Comment by jlandure** [comment]
For your information, the latest version installed is Chromium `77.0.3865.75-r0`.
We have to investigate to check what's the problem. 🙌

**Comment by mllopart** [comment]
In our case we changed our docker build to 

`chromium@edge=72.0.3626.121-r0`

That solved our problem for now in our Pipelines

**Comment by jlandure** [comment]
Hi @mllopart 👋 
Thanks for your reply! 

This is an option but you need to fork the project. 👌 
I'm thinking: why are not you using the image tag `zenika/alpine-chrome:72` instead of modifying the `Dockerfile` and built it by our own?
I am very interested! 👍

**Comment by teddy-error** [comment]
@jlandure This was of course the first attempted solution (much easier than cloning after all…) but interestingly using a static version tag did not resolve the issues.

**Comment by ardeois** [comment]
Thank you for the analysis.
I indeed got around the issue by fixing the version of the docker image. However, as we're using `with-node` tag, and this tag is not versioned, we had to duplicate what this Dockerfile is doing
https://github.com/Zenika/alpine-chrome/blob/0e0678f13b63556c1a6ec3a406de01ad0fc68b16/with-node/Dockerfile#L4-L9

I guess fixing this issue would have avoided that override, but it's not a big deal for now
https://github.com/Zenika/alpine-chrome/issues/38

**Comment by robwilde** [comment]
Thanks for the info. I investigated the apk installs and did just that. I found that if I replace @edge with @v3.9  it will complete the build and install chrome 72, then everything works.
A colleague had a similar issue and suggested it actually has something to do with the Linux Kernal version 5.0.0.27 and everything works OK with 5.0.0.25.

I can confirm that as I have one build running on Elementary OS (18.04 LTS) and it works just fine with @edge version and chrome 77 but on my laptop, running POP OS (19.04 confirmed to have Kernal 5.0.0.27) it does not work until v3.9 and chrome 72 
I did the test with Chrome 73 and it also fails.

Hope this helps

**Comment by chadlwilson** [comment]
This also ran into this with the `:with-node` images. Since we extend this image anyway; we could around it with a similar approach to @robwilde 

```
FROM zenika/alpine-chrome:with-node
USER root
# Workaround for https://github.com/Zenika/alpine-chrome/issues/39
RUN apk add --no-cache chromium@edge=73.0.3683.103-r0
USER chrome

# ...
```

Would be great if we could get versioned variants of the `with-node` tags here as these images are very convenient. :-)

**Comment by chadlwilson** [comment]
```
FROM zenika/alpine-chrome:with-node@sha256:a449df361d60dddef4f5b7de8d31e6c57d7a0feef74b6ac42b777fe30b7aef85
```
Is also an option for those who want to use the old image in its entirety - the one that had Chromium 76 prior to its removal from Alpine's repository.

**Comment by seanpianka** [comment]
@chadlwilson Why did you use `USER chrome` there, is there an issue using root?

**Comment by gamov** [comment]
> ```
> FROM zenika/alpine-chrome:with-node@sha256:a449df361d60dddef4f5b7de8d31e6c57d7a0feef74b6ac42b777fe30b7aef85
> ```
> 
> Is also an option for those who want to use the old image in its entirety - the one that had Chromium 76 prior to its removal from Alpine's repository.
> 
> ```
> $ chromium-browser --version
> Chromium 76.0.3809.132
> ```

Thank you for that!

**Comment by chadlwilson** [comment]
> @chadlwilson Why did you use `USER chrome` there, is there an issue using root?

The base [Dockerfile](https://github.com/Zenika/alpine-chrome/blob/master/Dockerfile)s run as `USER chrome` rather than `root`; so was just switching back to the same user as the base image for consistency (although running as non-root is good practice in general).

**Comment by jlandure** [comment]
Hi there 👋 

Sorry for the delay.
Thanks @chadlwilson for your precious replies. 💚 
Indeed, `with-node` has no version but I created the issue #38 to fix that. 👌 

Has someone investigated why `Chromium 77` create this error? 🤔

**Comment by jlandure** [comment]
For your information, I just manually published a `76-with-node` version for your needs.

```
docker container run -it --rm --entrypoint "" zenika/alpine-chrome:76-with-node chromium-browser --version

Chromium 76.0.3809.132 
```

**Comment by chadlwilson** [comment]
Thanks @jlandure - that's nicer than a direct SHA `FROM` instruction :-)

**Comment by paretl** [comment]
What about the one with the `with-puppeteer` tag ? This image has the exact same error with the latest version. For the moment I rebuild the image with the version 76 of Chrome.
@jlandure If you can publish a `76-with-puppeteer` version it would be very great :smile: 
Thank you in advance!

**Comment by FibreFoX** [comment]
As this issue is hitting other people too, did this issue already got reported to Alpine? Do you have any issue-tracker-link or such thing?

**Comment by wtayyeb** [comment]
@ardeois 
you need to uddate `libstdc++` to let chromium starts
`apk add libstdc++@edge`

**Comment by FibreFoX** [comment]
@wtayyeb I tried this, but did not work:
```sh
apk add --no-cache chromium@edge chromium-chromedriver@edge libstdc++@edge
```

Result: 
```
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt19_Sp_make_shared_tag5_S_eqERKSt9type_info: symbol not found
```
Looks like Alpine is broken, probably due to a missing patch or so :(

**Comment by jlandure** [comment]
Hi there!
I just tried @wtayyeb suggestion and it's working 🎉 
https://github.com/Zenika/alpine-chrome/pull/41

@paretl I've pushed a `76-with-puppeteer` version. See [here](https://cloud.docker.com/u/zenika/repository/docker/zenika/alpine-chrome/tags)

**Comment by jlandure** [comment]
For your information, it's hacktoberfest. Do not hesitate to create PR to support and improve this image 🙌 
More about [Hacktoberfest here](https://hacktoberfest.digitalocean.com/)

**Comment by paretl** [comment]
Thank you @jlandure 
I think it could be a great idea to have a tag with the chrome version for each one (in the future of course). It will permit to us to have a fix version of this image into our pipeline
We can talk about it if you want

**Comment by jlandure** [comment]
@paretl 💡 Yes Indeed. I'm trying to do it in #38 🙌

**Comment by jlandure** [comment]
Hey @paretl 👋 
You can now find new tags: 🎉 
- `with-node`, `77-with-node`, `77-with-node-10`
- `with-puppeteer`, `77-with-puppeteer`
See [README](https://github.com/Zenika/alpine-chrome) or [DockerHub](https://cloud.docker.com/u/zenika/repository/docker/zenika/alpine-chrome/tags) for more info

**Comment by ardeois** [comment]
Thank @jlandure 
I confirm using latest docker version fixed the issue.
Should I close this issue or I let you close it?

**Comment by jlandure** [comment]
Issue closed! Thanks everyone for your support 🎉 

Do not hesitate to give information on your usage with this image using the [issue template "support"](https://github.com/Zenika/alpine-chrome/issues/new?template=03_thanks.md).
I am thinking of refactoring the readme and add a contributor page like this [one](https://github.com/kefranabg/readme-md-generator#contributors)

**Comment by wtayyeb** [comment]
@FibreFoX full installation command is like below on a pure alpine1.10 image
```
    apk add --no-cache chromium@edge harfbuzz@edge nss@edge freetype@edge ttf-freefont@edge libstdc++@edge
```

**Comment by FibreFoX** [comment]
@wtayyeb ;) my problems are fixed now, switched our docker-image to be based on `alpine:edge`, due to the problem with mixing repositores having different glibc-stuff (which ends up not being able to get mixed that easy). I got to this issue "by accident" using DuckDuckGo because I found that `_ZNSt19_Sp_make_shared_tag5_S_eqERKSt9type_info: symbol not found`-stuff. So your solution did not work for me, so I created a new docker-image based on the same repository instead of mixed ones.

**Comment by jlandure** [comment]
Hi @FibreFoX 
Glad you succeed 🎉
I was wondering: why don't you update this repository to improve it and help others instead of forking or creating your own image? 🤔
It's hacktoberfest 🎉✌️

**Comment by jlandure** [comment]
@all-contributors please add @ardeois for bug

**Comment by jlandure** [comment]
@all-contributors please add @FibreFoX for question

**Comment by jlandure** [comment]
@all-contributors please add @chadlwilson for question and ideas
