### ISSUE TITLE
chrome 77 on stable alpine

### ISSUE THREAD

**Issue by fenchu** [Zenika/alpine-chrome#45]
Hi
I'm having stability issues with chromium77 on alpine edge, (selenium freezes), I like to use alpine stable (v3.10). I also like to use chromium76, the only chromium I found in stable was chrome73.
I currently use ubuntu 18.04 but it is 1.5GB large, while the alpine edge is only 384MB.

**Comment by jlandure** [comment]
Hi @fenchu 👋 

Thank you for your feedback.
Have you seen there is now dedicated tags for each Chromium version described [here](https://github.com/Zenika/alpine-chrome#supported-tags-and-respective-dockerfile-links)?

By the way, I don't understand your issue.
Is there a bug with its description? a request to add an ubuntu based image?

**Comment by fenchu** [comment]
Sorry for the confusion, I found the tags but they all work on 3.10.2 (edge), except for :73 which runs on 3.10.1, I like to run them all on 3.10.0, because this is what our software has been tested with. The problem with edge is that you suddenly gets a package update that may broke something.

**Comment by jlandure** [comment]
@all-contributors please add @fenchu for bug
