### ISSUE TITLE
Chromium package in v3.10 has upgraded to 77.x.x.x

### ISSUE THREAD

**Issue by nrawat151290** [Zenika/alpine-chrome#46]
We are using puppeteer 1.12.0 in our project. For this version, we need chromium 73.x.x.x which was present in v3.10 branch. Recently version has been upgraded to 77.x.x.x, which broke our application. can you pls mention the branch which has chromium 73.x.x.x package?

**Comment by jlandure** [comment]
Hi @nrawat151290 👋 

Thanks for your interest in this image! 👌 
Sorry for the delay. I was busy organizing a quite big conference called [DevFest Nantes](https://devfest.gdgnantes.com/)

I don't understand what's missing with the tag versions described [here](https://github.com/Zenika/alpine-chrome#supported-tags-and-respective-dockerfile-links)

```
$ docker container run -it --rm --entrypoint "" zenika/alpine-chrome:73 chromium-browser --version
Chromium 73.0.3683.103 

$ docker container run -it --rm --entrypoint "" zenika/alpine-chrome:73 cat /etc/alpine-release
3.10.1
```

What's next? 
Do you want me to create a `73-with-puppeteer` version with `puppeteer 1.12.0`?

Next time, please fill out the [form](https://github.com/Zenika/alpine-chrome/issues/new?assignees=&labels=bug&template=01_bug_report.md&title=) for `🐛 Bug report` to explain more precisely your issue. 👍 

And don't forget to fill out the [form](https://github.com/Zenika/alpine-chrome/issues/new?template=03_thanks.md) `❤️ Say thank you` form to explain your usecase with this image. 😇

**Comment by jlandure** [comment]
Hi @nrawat151290 
Any news regarding this issue?
Can I close it?

**Comment by jlandure** [comment]
@all-contributors please add @nrawat151290 for bug
