### ISSUE TITLE
Add `web-gl` by default?

### ISSUE THREAD

**Issue by jlandure** [Zenika/alpine-chrome#52]
**Context**

The base alpine-chrome is 135 MB. The `web-gl` one is 138 MB.
Does it make sense to add it by default? 🤔 

**Discussion**

Please help to decide 👍

**Comment by pxlrbt** [comment]
I don't think theres any sence in mantaining two images. It should be noted in the readme that you can disable GPU with `--disable-gpu` flag.

**Comment by jlandure** [comment]
✅  Already done with b7c44f62c0d0939a91e6cf0905bd16727cdbe559
Thanks @pxlrbt 👍
