### ISSUE TITLE
Add a new way to get the swiftshader libs

### ISSUE THREAD

**Issue by jlandure** [Zenika/alpine-chrome#53]
**Context**

Thanks to @pxlrbt we have the `so` libs compiled and available for swiftshader (see #50)

**Alternatives**

Can you achieve the same result doing that? 

It could be interesting to get or generate the libs without rebuilding Chrome (1,5 day), getting the generated APK, unpacking it and retrieving the `so` files.

```
RUN apk add --no-cache mesa-egl mesa-gles \
	&& rm -rf /var/lib/apt/lists/* \
    /var/cache/apk/* \
    /usr/share/man \
    /tmp/* \
    && mkdir /usr/lib/chromium/swiftshader/ \
    && cp /usr/lib/libGLESv2.so.2 /usr/lib/chromium/swiftshader/libGLESv2.so \
    && cp /usr/lib/libEGL.so.1 /usr/lib/chromium/swiftshader/libEGL.so
#    && ln -s /usr/lib/libGLESv2.so.2 /usr/lib/chromium/swiftshader/libGLESv2.so \
#    && ln -s /usr/lib/libEGL.so.1 /usr/lib/chromium/swiftshader/libEGL.so
# COPY swiftshader/libEGL.so /usr/lib/chromium/swiftshader/libEGL.so
# COPY swiftshader/libGLESv2.so /usr/lib/chromium/swiftshader/libGLESv2.so
RUN chmod 755 /usr/lib/chromium/swiftshader/libEGL.so
RUN chmod 755 /usr/lib/chromium/swiftshader/libGLESv2.so
```

It is not working... 😢 

** Other alternative **

See @lygstate info
https://github.com/Zenika/alpine-chrome/pull/50#issuecomment-612573824

What do you think?

**Comment by lygstate** [comment]
I didn't test it yet because of slow network, let's dig why

**Comment by pxlrbt** [comment]
What I just tried and what also did not work: `apk add mesa-dev`.
I also wanted to try to compile swiftshader on its own with from https://github.com/google/swiftshader but I'm getting stuck with:
```
==>CMake generation for OpenCL/MatrixMultiplication...
CMake Error at CMakeLists.txt:928 (add_custom_command):
  TARGET 'vk_swiftshader' was not created in this directory.
```

**Comment by jlandure** [comment]
Thanks @lygstate @pxlrbt for investigating! 🙌 

@lygstate @pxlrbt are you interested to be featured in the homepage. Can you describe with this [kind of issue](https://github.com/Zenika/alpine-chrome/issues/new?template=03_thanks.md) how you are using this image?

I will add a contributor section in the README. like here: https://github.com/zenika-open-source/awesome-remote-work

**Comment by lygstate** [comment]
I am not using this image anymore:) At the first time, I am just curious about why alpine chrome can not running webgl in docker:)....

**Comment by pxlrbt** [comment]
Well, I am actually also not using this image, but I am running an alpine image with PHP, Node and Puppeteer for generating complex PDFs.

**Comment by Niek** [comment]
Crossposting here for visibility:
- The swiftshader libs are now part of the Chromium aport, so no longer needed to copy them over: https://pkgs.alpinelinux.org/contents?file=lib*GL*&path=&name=chromium&branch=edge&arch=x86_64

And something else I noticed while benchmarking WebGL support:
- Switching to ``--use-gl=swiftshader`` does bump up the WebGL performance significantly compared to running without this parameter. However, the Canvas paint performance takes a big drop (see e.g. https://www.wirple.com/bmark/). Adding ``--disable-accelerated-2d-canvas`` helps a little but but it's still a long way to keep Canvas performance the same.

**Comment by jlandure** [comment]
Please have a look to this PR #100 🎉 

It's working for me using what @Niek said. 👍

If there is no bad news 😅  I will merge it tomorrow. 👌
