### ISSUE TITLE
add with selenium/playwright

### ISSUE THREAD

**Issue by x0rzkov** [Zenika/alpine-chrome#55]
Hi guys,

Hope you are doing well !

It would be awesome to have alpine chrome with selenium.

Is it something possible to add ?

Cheers,
X

**Comment by jlandure** [comment]
Hi @x0rzkov 

Yes I'm fine and you?
First of all, thanks for the suggestion. 👍 

What do you do with Selenium? 
Personally I haven't played with selenium for a long time so I didn't know how to install / manage / check that it's working. 😇 
Can you specify a little more the goals and an exemple of achievement?

Also have you tried dedicated docker image to selenium? [see here on the docker hub](https://hub.docker.com/search?q=selenium%20chrome&type=image)

Have a good day. ☀️

**Comment by x0rzkov** [comment]
Hi,

Thanks for your reply !

We (with a friend @lucmichalski) are doing some web scraping for building a cars dataset for deep learning purpose.
Ref. https://github.com/lucmichalski/cars-dataset
Example: https://github.com/lucmichalski/cars-dataset/blob/master/plugins/autotrader.com/crawler/crawler.go#L16

Nb. Have you considered to add https://github.com/microsoft/playwright also.
It would be an awesome replacement of puppeter.

Cheers,
X

**Comment by jlandure** [comment]
@all-contributors please add @x0rzkov for bug and ideas

**Comment by jlandure** [comment]
hey @x0rzkov 👋 

How are you?

I've tried to work with Playwright here at #85 
But the result is not very useful 😅 

Can you try this from your side to help me create the `with-playwright` tag?

**Comment by x0rzkov** [comment]
I sent you a DM on twitter because I have some questions to ask you about that and did not wanted to pollute this feed.

**Comment by jlandure** [comment]
Hi @x0rzkov 👋 

Thanks to @Niek I've updated the branch: the example using Playwright is working! 🎉 
Please check it out and send feedbacks! 

The `zenika/alpine-chrome:with-playwright` tag with a `Chromium 83` is working 🚀 

```sh
$ docker container run -it --rm -v $(pwd):/usr/src/app --cap-add=SYS_ADMIN zenika/alpine-chrome:with-playwright npm start

> zenika-alpinechrome-withplaywright@1.0.0 start /usr/src/app
> node src/useragent

Chromium 83.0.4103.61 
```

**Comment by jlandure** [comment]
Following the creation of the Playwright version, can I close this issue? 👍

**Comment by x0rzkov** [comment]
yes of course, thanks for everything !

**Comment by jlandure** [comment]
Please share the announcement: https://twitter.com/jlandure/status/1268175622230233091
And my post on dev.to here: https://dev.to/jlandure/crafting-the-perfect-container-to-play-with-a-headless-chrome-ilp
