### ISSUE TITLE
How can I remove page number when I use --print-to-pdf?

### ISSUE THREAD

**Issue by harobed** [Zenika/alpine-chrome#7]
How can I remove page number when I use --print-to-pdf?

**Comment by jlandure** [comment]
Humm there is multiple ways to achieve that:

1. With CSS
https://stackoverflow.com/questions/46077392/additional-options-in-chrome-headless-print-to-pdf

2. With DevTools protocol

https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF
There is projects to easily test that:
- https://pptr.dev/#?product=Puppeteer&version=v1.5.0&show=api-pagepdfoptions
- https://www.npmjs.com/package/chrome-headless-render-pdf

3. Cmd line?
No way for the moment: https://bugs.chromium.org/p/chromium/issues/detail?id=603559

**Comment by jlandure** [comment]
Hi @harobed did you solve your problems with page numbers?

**Comment by jlandure** [comment]
Hi @harobed 
Last call, I will close the issue in 3 days if you do not give any news...

**Comment by gitaaron** [comment]
I would recommend the second method you mentioned since the css method does not seem to work with many pages.
