### ISSUE TITLE
Update badges about size of the image 🙌

### ISSUE THREAD

**Issue by jlandure** [Zenika/alpine-chrome#88]
**Context**

See https://badgen.net/docker to use working badges
https://badgen.net/docker/size/zenika/alpine-chrome/latest

**Alternatives**
https://shields.io/
http://img.shields.io/docker/image-size/zenika/alpine-chrome/81

**Comment by neelkamath** [comment]
Can you assign this to me?

**Comment by neelkamath** [comment]
It looks like there's already a badge for the size of the layers ([reference](https://github.com/Zenika/alpine-chrome/commit/177258128a04fd8b612effb08c11e4b197e87902)). Should we close this issue, add the size badge in addition to the existing layers badge, or replace the layers badge?

**Comment by jlandure** [comment]
Hi @neelkamath 👋 

Thanks for your interest! 👍 

For the `latest` tag, I got `162MB` from [the Docker Hub](https://hub.docker.com/layers/zenika/alpine-chrome/latest/images/sha256-cbef07f4a2dbb346b22cc639e15e250adb74f094865b522d211780a5f20769a8?context=explore)

On Shields.io, I got `171MB` [here](https://img.shields.io/docker/image-size/zenika/alpine-chrome/latest)
On Badgen, I got `162MB` [here](https://badgen.net/docker/size/zenika/alpine-chrome/latest)

I think we could change the "Shields.io img size badge" by the "Badgen img size badge" to make more sense.

What do you think? 🤔 

Have a good day.

**Comment by neelkamath** [comment]
I can't find a "Shields.io img size badge", only a Mircrobadger one (i.e., `[![Layers](https://images.microbadger.com/badges/image/zenika/alpine-chrome.svg)](https://microbadger.com/images/zenika/alpine-chrome)`). Should I replace that? It does show 162 MB already though.

**Comment by jlandure** [comment]
Hi @neelkamath 👋 

Thanks for your investigation. 👍 

The badge from microbadger already in place seems to work well. 
We could close the issue. What do you think?

**Comment by neelkamath** [comment]
Yea, let's close it.

**Comment by jlandure** [comment]
@all-contributors please add @neelkamath for question
