### ISSUE TITLE
Remove the `with-webgl` tag

### ISSUE THREAD

**Issue by jlandure** [Zenika/alpine-chrome#97]
**Describe the bug**
Since the base image got the support of `webgl`, the `with-webgl` tag doesn't mean anything now.

- [x] Update README.md
- [x] Remove the `webgl` folder
- [x] Update the build on the Docker Hub

**Comment by Niek** [comment]
In addition to this, the ``libEGL.so`` and ``libGLESv2.so`` files are not (no longer?) needed. They are included in the Chromium aport: https://pkgs.alpinelinux.org/contents?file=lib*GL*&path=&name=chromium&branch=edge&arch=x86_64

**Comment by jlandure** [comment]
Hey @Niek 👋 

Thanks for the news. 👌 
I will check that. Related to #53 

By the way, @Niek feel free to describe your usage with this image [using this issue template](https://github.com/Zenika/alpine-chrome/issues/new?template=03_thanks.md)

**Comment by jlandure** [comment]
Fixes with #100
